---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-image:
    permissions:
      contents: write
    uses: martoc/workflow-container-image/.github/workflows/default.yml@v0
    secrets: inherit

